# this file defines a pipeline, a set of rules for building and validating source code in a repo
# written in a format called YAML 

# trigger defines when the pipeline will run
# list of branches syntax, if a branch gets a push, the pipeline will run

trigger:
  branches:
   include:
     - master
  paths: 
   include:
     - danielg-projectOne
     - azure-pipelines.yml
# short for agent pool as in "build agent"
# i.e. what set of machines will be the build agents to run these steps
pool:
  vmImage: 'ubuntu-latest'

# variables common to multiple steps
variables:
  buildConfiguration: 'Release'


# these steps are run in sequence by the build agent
# in a directory that contains the most recent push on that branch of that repo
# if any step fails, that will halt the build and subsequent steps will not run

steps:

#Added this task 12/3 
- task: UseDotNet@2
  displayName: dotnet package 
  inputs:
    packageType: 'sdk'
    version: 3.1.x

 
- task: SonarCloudPrepare@1
  displayName: sonar prepare anlysis
  inputs:
    SonarCloud: 'sonarcloud-projOne'
    organization: '2011-nov02-net'
    scannerMode: 'MSBuild'
    projectKey: '2011-nov02-net_danielg-project1'
    projectName: 'Project One Web App'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: danielg-projectOne

 
- task: SonarCloudAnalyze@1
  displayName: sonar run analysis

- task: SonarCloudPublish@1
  displayName: sonar analysis publish
  inputs:
    pollingTimeoutSec: '300'

# Added this task 12/3
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    workingDirectory: 'danielg-projectOne'

- script: dotnet publish --configuration $(buildConfiguration) --output publish
  displayName: 'dotnet publish'
  workingDirectory: danielg-projectOne

- task: AzureRmWebAppDeployment@4
  displayName: azure app service deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(f77db9df-7664-4dcc-ba6e-3fd840c8de99)'
    appType: 'webApp'
    WebAppName: 'dumb-mcdonalds-webapp'
    packageForLinux: 'danielg-projectOne/publish'